const browser = globalThis.browser || globalThis.chrome;

export async function detectWAF(targetUrl, signal = null) {
  let timeoutId = null;
  try {
    if (signal?.aborted) return { detected: false };
    const timeoutController = new AbortController();
    timeoutId = setTimeout(() => {
      try { timeoutController.abort(); } catch (e) {}
    }, 4000);

    let effectiveSignal = timeoutController.signal;
    if (signal) {
      if (typeof AbortSignal.any === 'function') {
        effectiveSignal = AbortSignal.any([signal, timeoutController.signal]);
      } else {
        signal.addEventListener('abort', () => {
          try { timeoutController.abort(); } catch (e) {}
        }, { once: true });
      }
    }

    const url = targetUrl.startsWith('http') ? targetUrl : `https://${targetUrl}`;
    const response = await fetch(url, {
      method: 'GET',
      redirect: 'follow',
      signal: effectiveSignal
    });
    if (timeoutId) clearTimeout(timeoutId);
    
    const headers = {};
    if (response.headers) {
      response.headers.forEach((value, key) => {
        headers[key.toLowerCase()] = value.toLowerCase();
      });
    }
    
    const status = response.status;
    const body = await response.text();
    const bodyLower = body.toLowerCase();
    
    // 1. Cloudflare Detection (Headers + Body + Cookies)
    if (headers['server']?.includes('cloudflare') ||
        headers['cf-mitigated'] ||
        headers['cf-ray'] ||
        headers['cf-cache-status'] ||
        bodyLower.includes('challenges.cloudflare.com') ||
        bodyLower.includes('cloudflare-static') ||
        bodyLower.includes('ray id:')) {
      const isChallenge = (status === 403 || status === 503) && 
        (bodyLower.includes('just a moment') || bodyLower.includes('cf-chl') || bodyLower.includes('challenge-platform'));
      return {
        detected: true,
        vendor: 'Cloudflare',
        type: 'proxy',
        challenge: isChallenge,
        cdnOnly: !isChallenge && status < 400
      };
    }
    
    // 2. Sucuri CloudProxy
    if (headers['server']?.includes('sucuri') ||
        headers['x-sucuri-id'] ||
        headers['x-sucuri-cache'] ||
        bodyLower.includes('sucuri website firewall')) {
      const isBlocked = status === 403 || bodyLower.includes('access denied') || bodyLower.includes('sucuri website firewall');
      return {
        detected: true,
        vendor: 'Sucuri CloudProxy',
        type: 'proxy',
        challenge: isBlocked
      };
    }
    
    // 3. Imperva / Incapsula
    if (headers['x-iinfo'] ||
        headers['x-cdn']?.includes('incapsula') ||
        bodyLower.includes('incapsula incident id') ||
        bodyLower.includes('_incapsula_resource')) {
      return {
        detected: true,
        vendor: 'Imperva Incapsula',
        type: 'proxy',
        challenge: status === 403
      };
    }

    // 4. Akamai
    if (headers['x-akamai-transformed'] ||
        headers['server']?.includes('akamaighost')) {
      return {
        detected: true,
        vendor: 'Akamai WAF/CDN',
        type: 'proxy',
        challenge: status === 403
      };
    }

    // 5. AWS WAF / CloudFront
    if (headers['x-amz-cf-id'] || headers['x-amzn-waf-action'] || headers['x-amzn-errortype']?.includes('waf')) {
      return {
        detected: true,
        vendor: 'AWS CloudFront / AWS WAF',
        type: 'proxy',
        challenge: status === 403
      };
    }

    // 6. Fastly
    if (headers['x-fastly-request-id']) {
      return {
        detected: true,
        vendor: 'Fastly',
        type: 'proxy',
        challenge: status === 403
      };
    }

    // 7. LiteSpeed Web ADC / WAF
    if (headers['server']?.includes('litespeed') || headers['x-litespeed-cache']) {
      return {
        detected: true,
        vendor: 'LiteSpeed / QUIC.cloud',
        type: 'proxy',
        challenge: status === 403
      };
    }
    
    // 8. Wordfence plugin firewall
    if (bodyLower.includes('wordfence') || 
        bodyLower.includes('wfvt_') ||
        bodyLower.includes('wfls-') ||
        headers['set-cookie']?.includes('wfvt_') ||
        headers['set-cookie']?.includes('wfls-')) {
      const isChallenge = status === 403 || bodyLower.includes('your access to this site has been limited') || bodyLower.includes('generated by wordfence');
      return {
        detected: true,
        vendor: 'Wordfence Security',
        type: 'plugin',
        challenge: isChallenge
      };
    }

    // 9. NinjaFirewall
    if (bodyLower.includes('ninjafirewall') || bodyLower.includes('403 forbidden (nfw)')) {
      return {
        detected: true,
        vendor: 'NinjaFirewall',
        type: 'plugin',
        challenge: true
      };
    }
    
    // 10. Generic 403/503 blocking with short body
    if ((status === 403 || status === 503) && body.length < 500) {
      return { detected: true, vendor: 'Unknown WAF', type: 'unknown', challenge: true };
    }
    
    return { detected: false, vendor: null };
    
  } catch (err) {
    return { detected: false, vendor: null, error: err.message };
  }
}
